
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;

import block.Block;

public class Main {

	public static void main(String[] args) throws NoSuchAlgorithmException {

		ArrayList<Block> myList = new ArrayList<>(3);
		
		Block b1 = new Block("Hello, I am block 1", "null");
		Block b2 = new Block("Hello, I am block 2", b1.getHash());
		Block b3 = new Block("Hello, I am block 3", b2.getHash());

		myList.add(b1);
		myList.add(b2);
		myList.add(b3);

		System.out.println("HashCode Generated by SHA-256 for:");

		for (int x = 0; x < myList.size(); x++) {
			Block block = myList.get(x);
			System.out.println("BlockID: " + block.getBlockId());
			System.out.println("PreviousBlockHash: " + block.getPreviousHash());
			System.out.println("Timestamp: " + block.getTimeStamp());
		}
		
	}

}
